### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SimpleMarcel** [yunglean4171/License-API-System#1]
Hello, can you add an IP check for fivem because everyone else could use this key, which is not wanted

**Comment by yunglean4171** [comment]
Hey, There is ip checking as you can see id variable in fivem case is equal to server ip.

<img width="1086" alt="Screenshot at Apr 16 18-40-04" src="https://user-images.githubusercontent.com/71585779/163683815-dd2bac22-d081-4bae-8fef-27bb241b5521.png">

License checking function is simply "AND" logic gate it means both values (lickey and id) has to match in database to pass auth.

<img width="779" alt="Screenshot at Apr 16 18-40-38" src="https://user-images.githubusercontent.com/71585779/163683763-26cad39a-3b2e-4819-81ba-58d657818856.png">

**Comment by SimpleMarcel** [comment]
Thank i didn`t see it
