### ISSUE TITLE
I have Problems with Python

### ISSUE THREAD

**Issue by SimpleMarcel** [yunglean4171/License-API-System#2]
What Python version do you have?
![Screenshot 2022-04-16 200223](https://user-images.githubusercontent.com/102701262/163686388-7d02119f-3789-4086-bc4b-97470cd8cf76.png)

**Comment by yunglean4171** [comment]
3.9.12
<img width="150" alt="Screenshot at Apr 16 20-28-23" src="https://user-images.githubusercontent.com/71585779/163687111-64022203-daad-430f-99ca-1564751cf583.png">

**Comment by yunglean4171** [comment]
![Screenshot at Apr 16 20-37-46](https://user-images.githubusercontent.com/71585779/163687378-106262a9-29ed-4171-b540-780afecd88ba.png)

I guess the problem is wit flask version

**Comment by yunglean4171** [comment]
try to install 2.1.0 version and let me know if that helped

**Comment by SimpleMarcel** [comment]
i will try it thanks

**Comment by SimpleMarcel** [comment]
I have now the problem:

C:\xampp\htdocs>python api.py
Traceback (most recent call last):
  File "C:\xampp\htdocs\api.py", line 3, in <module>
    import mysql.connector
  File "C:\Users\marce\AppData\Local\Programs\Python\Python39-32\lib\site-packages\mysql\connector\__init__.py", line 34, in <module>
    import _version
ModuleNotFoundError: No module named '_version'

**Comment by yunglean4171** [comment]
```
python -m pip install mysql-connector-python
```
try this

**Comment by SimpleMarcel** [comment]
Does it work now, I'm not very familiar with it

Message:
C:\xampp\htdocs>python api.py
 * Serving Flask app 'api' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 116-850-219

**Comment by SimpleMarcel** [comment]
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by yunglean4171** [comment]
> Does it work now, I'm not very familiar with it
> 
> Message: C:\xampp\htdocs>python api.py
> 
> * Serving Flask app 'api' (lazy loading)
> * Environment: production
>   WARNING: This is a development server. Do not use it in a production deployment.
>   Use a production WSGI server instead.
> * Debug mode: on
> * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
> * Restarting with stat
> * Debugger is active!
> * Debugger PIN: 116-850-219

it mean that api script ran successfully

**Comment by yunglean4171** [comment]
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

when is this error appear?

**Comment by yunglean4171** [comment]
and also there is no need to "host" api.py in htdocs, script is not website, you can keep it anywhere and just run python api.py command to start it

**Comment by SimpleMarcel** [comment]
when I connect to the url

**Comment by SimpleMarcel** [comment]
C:\xampp\htdocs>python api.py
 * Serving Flask app 'api' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 116-850-219
127.0.0.1 - - [16/Apr/2022 20:51:34] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [16/Apr/2022 20:51:34] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [16/Apr/2022 20:53:26] "GET / HTTP/1.1" 404 -

**Comment by yunglean4171** [comment]
it wont work while u connect thru browser

**Comment by yunglean4171** [comment]
if u want to manage lkeys u have to use postman or write simple scripts in python

**Comment by yunglean4171** [comment]
requests.get, post, delete

**Comment by SimpleMarcel** [comment]
oh thanks i'm so lost

**Comment by yunglean4171** [comment]
np if u need help with installation etc hmu on discord yunglean_#4171

**Comment by SimpleMarcel** [comment]
Thanks I'll try everything now and I'll let you know if I have any problems
